# 服务端口
server:
  port: 8010
  # 服务名
spring:
  application:
    name: service-gateway
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 175.178.189.89:12208
    #使用服务发现路由

    gateway:
      discovery:
        locator:
          enabled: true
      #服务路由名小写
      #spring.cloud.gateway.discovery.locator.lower-case-org.snbo.aclService.service-id=true
      #设置路由id
      routes:
        - id: db-acl
          #设置路由的uri
          uri: lb://db-acl
          #设置路由断言,代理servicerId为auth-service的/auth/路径
          predicates:
            - Path=/*/acl/**
        #配置service-edu服务

        - id: db-service
          uri: lb://db-service
          predicates:
            - Path=/db/**
        #配置service-ucenter服务

        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/eduOss/**
